### ISSUE TITLE
Cycles/ifs are broken in CdM8-e

### ISSUE THREAD

**Issue by e-buzyurkin** [cdm-processors/cdm-devkit#30]
**Describe the bug**
File does not compile in cocas with target cdm8e, but compiles in CocoIDE

**To Reproduce**
1. Run `python3 cdm-devkit/cocas/main.py -t cdm8e main.asm` in terminal
2. See error

```
[Assembler] ERROR at line 0 of unknown
'$21_finally'
```

**Expected behavior**
Expected to get .img file from cocas.

**Environment**
 - OS: MacOS Monterey 12.6.3; resulted with the same error on my teammate's laptop with Windows  
 - Devkit version: 0.1.2
 - Python version: 3.11.1
 - ANTLR Runtime version: 4.11.1

**Additional context**
GitHub does not support .asm files, so file format was changed to .txt without changes in content.

[main.asm.txt](https://github.com/cdm-processors/cdm-devkit/files/10958759/main.asm.txt)

[main.asm.zip](https://github.com/cdm-processors/cdm-devkit/files/10958815/main.asm.zip)

**Comment by cjvth** [comment]
This issue was caused by temporary labels were expected to be in a list with common labels. It was fixed for CdM-16 in 3a24e6d2, but I forgot to change for the other target
