### ISSUE TITLE
Tester cannot parse zero from YAML document

### ISSUE THREAD

**Issue by andrey-dru-me1** [cdm-processors/cdm-devkit#47]
**Describe the bug**
Test is marked as SKIPPED and `SKIPPED [2] tests/factory/tools.py:27: circuit state specification parsing failed` is shown in terminal output when there is zero in any memory cell at .yaml doc.

**To Reproduce**
1. Create files tests/resources/cdm16/output/alu_flags.yaml and tests/resources/cdm16/input/alu_flags.asm
2. Write something like
    ```yaml
    memory:
        0xfffe: 0
    ```
    in alu_flags.yaml
3. Write some correct code in alu_flags.asm (no matter what: in correct case tester should output either `PASSED` or `FAILED`)
4.  Execute in terminal `pytest --tb=no -rA -v`

**Expected behavior**
Either `PASSED` or `FAILED` new cdm16-alu_flags test.

**Comment by Intelix8996** [comment]
Tester fills memory with zeros on start, so comparing memory location against zero is invalid as you can't distinguish whether zero was written or nothing was written at all.
